#
# Nmake file - Windows version
# Use 'nmake -f Makefile.win'

NODEBUG=1

INCS = /I..
OPTS = -D_CRT_SECURE_NO_WARNINGS
LIBS = ../libmseed.lib
BINS = msview.exe

all: $(BINS)

msview.exe: msview.obj
	link.exe /nologo /out:msview.exe $(LIBS) msview.obj

.c.obj:
	$(CC) /nologo $(CFLAGS) $(INCS) $(OPTS) /c $<

# Clean-up directives
clean:
	-del a.out core *.o *.obj *% *~ $(BINS)
