var searchData=
[
  ['i_20contribute_0',['This library is great, but doesn&apos;t do something I need. What can I do? How can I contribute?',['../page-faq.html#faq-10',1,'']]],
  ['i_20do_1',['This library sucks. What can I do?',['../page-faq.html#faq-9',1,'']]],
  ['i_20do_20how_20can_20i_20contribute_2',['This library is great, but doesn&apos;t do something I need. What can I do? How can I contribute?',['../page-faq.html#faq-10',1,'']]],
  ['i_20do_20that_3',['I&apos;m using the library and would like to cite it. How do I do that?',['../page-faq.html#faq-8',1,'']]],
  ['i_20m_20using_20the_20library_20and_20would_20like_20to_20cite_20it_20how_20do_20i_20do_20that_4',['I&apos;m using the library and would like to cite it. How do I do that?',['../page-faq.html#faq-8',1,'']]],
  ['i_20need_20to_20use_20separate_20fdsn_20identifiers_20of_20network_20station_20location_20and_20channel_5',['I need to use separate FDSN identifiers of Network, Station, Location and Channel.',['../page-faq.html#faq-6',1,'']]],
  ['i_20need_20what_20can_20i_20do_20how_20can_20i_20contribute_6',['This library is great, but doesn&apos;t do something I need. What can I do? How can I contribute?',['../page-faq.html#faq-10',1,'']]],
  ['i_20o_7',['File and URL I/O',['../group__io-functions.html',1,'']]],
  ['i_20port_20my_20libmseed_202_20x_20program_20to_20the_203_20x_20api_8',['The library API changed! Why? How do I port my libmseed 2.x program to the 3.x API?',['../page-faq.html#faq-7',1,'']]],
  ['i_20read_20data_20from_20a_20url_9',['How do I read data from a URL?',['../page-faq.html#faq-3',1,'']]],
  ['i_20read_20write_20data_20from_20to_20files_10',['How do I read/write data from/to files?',['../page-faq.html#faq-1',1,'']]],
  ['i_20read_20write_20data_20from_20to_20memory_20buffers_11',['Can I read/write data from/to memory buffers?',['../page-faq.html#faq-2',1,'']]],
  ['i_20use_20libmseed_20strictly_20with_20miniseed_20version_202_12',['Can I use libmseed strictly with miniSEED version 2?',['../page-faq.html#faq-5',1,'']]],
  ['identifiers_13',['Identifiers',['../group__string-functions.html',1,'Source Identifiers'],['../page-examples.html#example-lm_sids',1,'Working with Source Identifiers']]],
  ['identifiers_20of_20network_20station_20location_20and_20channel_14',['I need to use separate FDSN identifiers of Network, Station, Location and Channel.',['../page-faq.html#faq-6',1,'']]],
  ['important_20changes_20that_20commonly_20need_20attention_15',['Most important changes that commonly need attention',['../porting-guide.html#porting-important',1,'']]],
  ['in_20data_20model_16',['Ramifications for change in data model',['../porting-guide.html#porting-data-model-change',1,'']]],
  ['in_20parallel_17',['Reading files in parallel',['../page-examples.html#example-lm_pararead',1,'']]],
  ['input_18',['input',['../group__io-functions.html#a6e1e020cfbb1407cdcdccde713bd4b84',1,'MS3FileParam']]],
  ['inputchannel_19',['inputchannel',['../group__extra-headers.html#a1b71af7e6b36aefd63fd3a3c5c408cca',1,'MSEHCalibration']]],
  ['inputunits_20',['inputunits',['../group__extra-headers.html#aaacb7fe7f366cbda2a72f5a7c4437693',1,'MSEHCalibration']]],
  ['installing_21',['Downloading and installing',['../index.html#main-downloding',1,'']]],
  ['into_20traces_20lists_22',['Reading miniSEED from files into traces lists',['../page-tutorial.html#reading-tracelists',1,'']]],
  ['is_20a_20library_20needed_23',['miniSEED is simple, why is a library needed?',['../page-faq.html#faq-4',1,'']]],
  ['is_20great_20but_20doesn_20t_20do_20something_20i_20need_20what_20can_20i_20do_20how_20can_20i_20contribute_24',['This library is great, but doesn&apos;t do something I need. What can I do? How can I contribute?',['../page-faq.html#faq-10',1,'']]],
  ['is_20simple_20why_20is_20a_20library_20needed_25',['miniSEED is simple, why is a library needed?',['../page-faq.html#faq-4',1,'']]],
  ['issues_26',['Development and issues',['../index.html#develop-main',1,'']]],
  ['it_20how_20do_20i_20do_20that_27',['I&apos;m using the library and would like to cite it. How do I do that?',['../page-faq.html#faq-8',1,'']]]
];
